const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
class Worker{constructor(){this.messages=[];Worker.last=this;}postMessage(data){this.messages.push(data);}terminate(){this.terminated=true;}reply(data){this.onmessage({data});}}
const scope={Worker,FlyVision:{},console,Uint8ClampedArray,Promise};vm.createContext(scope);vm.runInContext(fs.readFileSync('vision-client.js','utf8'),scope);
const retina=new scope.FlyVision.AsyncRetina({eyes:[]}),worker=Worker.last,texture={width:1,height:1,data:new Uint8ClampedArray([120,120,120,255])};
retina.update({x:.1},texture,1/60);assert.equal(worker.messages.length,1,'wait for worker initialization');worker.reply({type:'ready'});assert.equal(worker.messages.length,2);assert.equal(worker.messages[1].texture,texture);
for(let i=0;i<20;i++)retina.update({x:i},texture,1/60);assert.equal(worker.messages.length,2,'only one request can be in flight');worker.reply({type:'frame',frames:[{},{}],signal:[.2,.3]});
const pending=worker.messages[2];assert.equal(pending.pose.x,19,'latest pose replaces stale queued poses');assert(Math.abs(pending.dt-20/60)<1e-10,'elapsed neural simulation time is preserved');assert.equal(pending.texture,undefined,'unchanged texture is not repeatedly copied');
const replaced={...texture};retina.update({x:.5},replaced,0);worker.reply({type:'frame',frames:[{},{}],signal:[.4,.5]});assert.equal(worker.messages[3].texture,replaced,'food/daylight texture changes reach worker');assert.deepEqual(retina.signal,[.4,.5]);retina.dispose();assert(worker.terminated,'reset releases old worker');
const {Retina}=require('./vision');const r=new Retina(require('./eye-map.json')),pose={x:.32,y:.42,z:.12,heading:0,light:.7};let traces=0;const trace=r.room.trace.bind(r.room);r.room.trace=(...args)=>{traces++;return trace(...args);};r.update(pose,texture,1/60);const first=traces;r.update(pose,texture,1/60);assert.equal(traces,first,'stationary optics reuse capture while neural dynamics continue');r.update({...pose,heading:.1},texture,1/60);assert(traces>first,'turn invalidates optical cache');
const {linear}=require('./visual-circuit');for(let i=0;i<=2048;i++){const v=i/2048,expected=v<=.04045?v/12.92:((v+.055)/1.055)**2.4;assert(Math.abs(linear(v*255)-expected)<1e-7,'transfer table preserves linear light');}
const replies=[],backend={performance:require('node:perf_hooks').performance,postMessage:data=>replies.push(data),console};vm.createContext(backend);backend.importScripts=(...names)=>{for(const name of names)vm.runInContext(fs.readFileSync(name.split('?')[0],'utf8'),backend);};vm.runInContext(fs.readFileSync('vision-worker.js','utf8'),backend);backend.onmessage({data:{type:'init',map:require('./eye-map.json')}});backend.onmessage({data:{type:'update',pose,texture,dt:1/60}});assert.equal(replies[0].type,'ready');assert.equal(replies[1].type,'frame');assert.equal(replies[1].frames[0].data.length,160*128*4);assert(replies[1].signal.every(Number.isFinite),'actual worker backend delivers sensory signals');
console.log('PASS worker backpressure, elapsed time, texture invalidation, reset cleanup, stationary capture reuse and turn invalidation');
